# Generated by Django 5.2 on 2025-05-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritos',
            name='tipo',
            field=models.CharField(choices=[('movie', 'Filme'), ('tv', 'Série')], default='movie', max_length=10),
        ),
    ]
